### ISSUE TITLE
出羽指摘事項

### ISSUE THREAD

**Issue by tdewa** [saga0520/practice#1]
https://github.com/saga0520/practice/commit/d39d9c07d94ae865e961e1d9a38642295caf726b
https://github.com/saga0520/practice/commit/4980aee01ddfa5b2ed31e1e7878fbe51806e9df9

PHPでもShift-Jisは無いと言われるなか
Javaの内部エンコードさえUnicodeと言われているのにこれはないです。
https://ja.wikipedia.org/wiki/Unicode

**Comment by tdewa** [comment]
修正ありがとうございます。
まず、git command覚えよう。
https://qiita.com/annyamonnya/items/d845597606fbabaabcad
https://qiita.com/shuntaro_tamura/items/06281261d893acf049ed
`削除`というコミットは消せました。やらかした場合はまず落ち着こう。
深呼吸深呼吸。

指摘箇所を２箇所入れましたのでご確認お願い致します。
https://github.com/saga0520/practice/commit/12cabadf30545878f0a02eddcb4a0cdd04f95497

**Comment by tdewa** [comment]
英単語の意味が知りたいです、、、
https://github.com/saga0520/practice/commit/0bb3bb0ce795a5a2904c1d47f3a2f19c6977a5e3

**Comment by saga-76** [comment]
あ”あ”－すいません間違えていました…

**Comment by tdewa** [comment]
う〜ん
https://github.com/saga0520/practice/commit/037a7e0d7e052daab53affff7509f14eb0178c6c

**Comment by saga-76** [comment]
入力値を返すのでChoiceはないでした…値なのでValueが相応しいでしたか。

**Comment by tdewa** [comment]
抽象的から具体的な単語に変更お願いします。
https://github.com/saga0520/practice/commit/da8f8c24f6b3886c3378222a7ad4ad288e36131a
依頼事項は２点
１．git resetから始まる歴史改ざんと呼ばれる方法を使い、直前のコミット「戻り値、変数名修正」を削除するgitコマンド練習
２．getValueの名称変更

**Comment by saga-76** [comment]
戻り値resultValも変更しましたので、以下３点を行い、修正致しました。
１．git resetで前回のコミットを取り消す。
２．getValueをgetConsolValに変更。
３．resultValをresultConsolValに変更。

**Comment by tdewa** [comment]
すみません、指摘見逃しが一箇所残っておりましたorz
修正よろしくお願い致します。
https://github.com/saga0520/practice/commit/c2e203d9626c08ff486e6c8309336b92b21c0214

**Comment by tdewa** [comment]
修正は間違いではなかったのですが、
コメントを意識せずに付けられたようなので厳しいコメントを書き入れました
ご確認よろしくお願いします。
https://github.com/saga0520/practice/commit/b7cc1cf849e9922187ab18975c4d21ff2ef08b2b

**Comment by tdewa** [comment]
コメントに対して配慮するということなので、
コメント見直し指摘をガッツリと入れさせて頂きました。
ご確認よろしくお願いします。
https://github.com/saga0520/practice/commit/e9d8a7e6b10532b3d5dcedd63e0dad647bf91f58

**Comment by tdewa** [comment]
バッチリだと思います。
お疲れ様でした。
